### ISSUE TITLE
s2s API requests & unauthorized usage

### ISSUE THREAD

**Issue by frozenpandaman** [zeroday0619/Nintendo_Switch_Online_API_Bridge#1]
Hi,

Users of this project are absolutely hammering my personal webserver and making the s2s API impossible to use for anyone else. Please check your code since something seems to be acting up, sending countless requests over and over.

![image](https://user-images.githubusercontent.com/7245874/174779655-bee56aea-3dca-42ee-b68a-2ce31737d88f.png)

In addition, the [splatnet2statink API docs](https://github.com/frozenpandaman/splatnet2statink/wiki/api-docs) that you much reach out to me for permission to use my API. Correct me if I'm mistaken or if I forgot something, but I'm unfamiliar with this project and you have not contacted me previously.

**Comment by zeroday0619** [comment]
@frozenpandaman sorry. I found out about this now. I'm going to make the project private and take it down from pypi asap.

**Comment by zeroday0619** [comment]
@frozenpandaman Modified s2s api to be deprecated.
