### ISSUE TITLE
need guide about example getSelf

### ISSUE THREAD

**Issue by SuFIND** [zeroday0619/Nintendo_Switch_Online_API_Bridge#2]
Helllo,
- my problem
  It's my first time learn how to use nintendo restuf api.
  This part should I replace to my self session token?
  ![image](https://user-images.githubusercontent.com/30424839/186610029-dc4cc42d-7487-4dff-9901-c46303615f98.png)
  
  When I'm  try to run the demo code "GetSelf" in README.md, I get the tip. What is mean?
  ![image](https://user-images.githubusercontent.com/30424839/186606493-60c528b1-486c-49b7-88ee-512da47d0fa6.png)
  
  Can someone tell me what url should I used in here? Can someone give some examples？

 - other
  I want to develop a program to auto invite other members to join the family. When I read nsa.py and nao.py, I don't find any api about Family.  Is mean no possible to get apis family?

**Comment by zeroday0619** [comment]
@SuFIND 
callback url:
![Screenshot_20220919_160135](https://user-images.githubusercontent.com/54426648/190965212-b6fc3965-a5c3-463e-8ced-18dc747aa886.png)

Session tokens are automatically generated and stored in the keychain.

**Comment by shiruva** [comment]
How do I get to that screen? I looked it up and couldn't figure it out.

**Comment by SuFIND** [comment]
> @SuFIND callback url: ![Screenshot_20220919_160135](https://user-images.githubusercontent.com/54426648/190965212-b6fc3965-a5c3-463e-8ced-18dc747aa886.png)
> 
> Session tokens are automatically generated and stored in the keychain.

real thks
